### ISSUE TITLE
No package matching 'gnupg2' is available

### ISSUE THREAD

**Issue by jc36** [geerlingguy/ansible-role-fluentd#3]
I have an error when install fluentd:
```
TASK [geerlingguy.fluentd : Add required dependencies.] ***********************************************************************************************************************************************************
fatal: [54.93.207.197]: FAILED! => {"changed": false, "msg": "No package matching 'gnupg2' is available"}
```
It was resolved with pre_task:
```
- hosts: fluentd
  become: yes
  pre_tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes
  roles:
    - role: geerlingguy.fluentd
      tags:
        - fluentd
```
